import { Link } from 'react-router-dom'
import {
  Sparkles,
  PenTool,
  FileCheck2,
  FlaskConical,
  FileText,
  MessageSquare,
  Youtube,
  Image,
  BookOpen,
  History,
  PenSquare,
  HeartHandshake,
  BarChart3,
  CalendarDays,
  Lightbulb,
} from 'lucide-react'

const DashboardHome = () => {
  const quickActions = [
    {
      label: 'Plan a Lesson',
      description: 'Generate a standards-aligned lesson outline in minutes.',
      icon: PenTool,
      path: '/dashboard/templates/general-lesson-planner',
    },
    {
      label: 'Create an Assessment',
      description: 'Build formative or summative checks for understanding.',
      icon: FileCheck2,
      path: '/dashboard/templates/summative-assessment-builder',
    },
    {
      label: 'Design a STEM Lab',
      description: 'Craft hands-on STEM experiences tailored to your class.',
      icon: FlaskConical,
      path: '/dashboard/templates/experiment-idea-generator',
    },
  ]

  const featureWorkflows = [
    {
      path: '/dashboard/templates',
      icon: FileText,
      title: 'Templates Library',
      description: 'Access a wide range of teaching templates and resources.',
      color: 'bg-blue-500',
    },
    {
      path: '/dashboard/chatbots',
      icon: MessageSquare,
      title: 'Specialized Chatbots',
      description: 'Interact with AI chatbots designed for specific teaching needs.',
      color: 'bg-green-500',
    },
    {
      path: '/dashboard/youtube-quiz',
      icon: Youtube,
      title: 'YouTube Quiz Generator',
      description: 'Create engaging quizzes from YouTube videos automatically.',
      color: 'bg-red-500',
    },
    {
      path: '/dashboard/pixgen',
      icon: Image,
      title: 'PixGen (AI Media Studio)',
      description: 'Generate and edit images with AI-powered tools.',
      color: 'bg-purple-500',
    },
    {
      path: '/dashboard/learning-hub',
      icon: BookOpen,
      title: 'Professional Learning Hub',
      description: 'Access professional development resources and courses.',
      color: 'bg-orange-500',
    },
    {
      path: '/dashboard/history',
      icon: History,
      title: 'History & Personalization',
      description: 'View your activity history and personalize your experience.',
      color: 'bg-indigo-500',
    },
  ]

  const recommendedTemplates = [
    {
      title: 'Homework Assignment Creator',
      description: 'Differentiate take-home practice with voice and choice.',
      icon: PenSquare,
      path: '/dashboard/templates/activity-planner',
    },
    {
      title: 'Activities for SEL',
      description: 'Support social-emotional growth with ready-to-use routines.',
      icon: HeartHandshake,
      path: '/dashboard/templates',
    },
    {
      title: 'Data & Statistics Scenario Builder',
      description: 'Bring data literacy to life with authentic case studies.',
      icon: BarChart3,
      path: '/dashboard/templates/data-statistics-scenario-builder',
    },
  ]

  const insightHighlights = [
    {
      title: 'Upcoming PD: AI in the Classroom',
      description: 'Join our live webinar this Thursday at 4 PM to explore AI-driven lesson design.',
      icon: CalendarDays,
    },
    {
      title: 'Teaching Tip of the Week',
      description: 'Use exit tickets generated by the Formative Assessment tool to close every lesson with evidence.',
      icon: Lightbulb,
    },
    {
      title: 'Team Update',
      description: 'The templates library now includes 10 new cross-curricular units recommended by coaches.',
      icon: BookOpen,
    },
  ]

  return (
    <div className="space-y-10">
      {/* Hero Section */}
      <div className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-6">
        <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-primary-600 via-primary-500 to-indigo-500 p-8 text-white shadow-lg">
          <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_top,_var(--tw-gradient-stops))]" />
          <div className="relative z-10 max-w-2xl space-y-4">
            <div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-sm font-medium">
              <Sparkles className="h-4 w-4" />
              AI-Enhanced Planning Hub
            </div>
            <h1 className="text-3xl font-bold lg:text-4xl">Welcome back—let’s build something great for your learners.</h1>
            <p className="text-white/80">
              Jump back into your planning flow with quick actions, recommended templates, and insights curated
              from educators using the Teacher Assistant platform.
            </p>
            <div className="flex flex-wrap gap-3">
              <Link
                to="/dashboard/templates"
                className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-primary-600 shadow-sm transition hover:bg-primary-50"
              >
                Browse Templates
              </Link>
              <Link
                to="/dashboard/chatbots"
                className="inline-flex items-center gap-2 rounded-lg border border-white/40 px-4 py-2 text-sm font-semibold text-white transition hover:bg-white/10"
              >
                Ask a Teaching Coach
              </Link>
            </div>
          </div>
        </div>

        <div className="grid gap-4">
          <div className="card bg-white/60">
            <p className="text-sm text-gray-500">Active Projects</p>
            <p className="text-3xl font-semibold text-gray-900">4</p>
            <p className="mt-2 text-sm text-gray-600">You’re collaborating on lesson plans across science and humanities this week.</p>
          </div>
          <div className="card bg-white/60">
            <p className="text-sm text-gray-500">Suggested Next Step</p>
            <p className="mt-2 text-sm text-gray-700">
              Finish the assessment for your <span className="font-medium">Grade 8 Forces & Motion</span> unit and share it with your team.
            </p>
          </div>
        </div>
      </div>

      {/* Quick Metrics */}
      <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
        <div className="card">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Templates Created</p>
              <p className="text-2xl font-semibold text-gray-900">12</p>
            </div>
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100">
              <FileText className="h-6 w-6 text-blue-600" />
            </div>
          </div>
          <p className="mt-3 text-xs text-gray-500">+3 this week</p>
        </div>

        <div className="card">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Chat Sessions</p>
              <p className="text-2xl font-semibold text-gray-900">18</p>
            </div>
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-green-100">
              <MessageSquare className="h-6 w-6 text-green-600" />
            </div>
          </div>
          <p className="mt-3 text-xs text-gray-500">Mostly focused on feedback strategies</p>
        </div>

        <div className="card">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Quizzes Generated</p>
              <p className="text-2xl font-semibold text-gray-900">6</p>
            </div>
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-red-100">
              <Youtube className="h-6 w-6 text-red-600" />
            </div>
          </div>
          <p className="mt-3 text-xs text-gray-500">Two linked to the Space Exploration playlist</p>
        </div>
      </div>

      {/* Quick Actions */}
      <section>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-semibold text-gray-900">Quick actions</h2>
          <Link to="/dashboard/templates" className="text-sm font-semibold text-primary-600 hover:text-primary-500">
            View all workflows
          </Link>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {quickActions.map((action) => {
            const Icon = action.icon
            return (
              <Link
                key={action.label}
                to={action.path}
                className="card group border border-primary-100/60 hover:border-primary-200 hover:shadow-md transition"
              >
                <div className="flex items-start gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary-50 text-primary-600 group-hover:bg-primary-100">
                    <Icon className="h-6 w-6" />
                  </div>
                  <div className="flex-1">
                    <p className="font-semibold text-gray-900 group-hover:text-primary-600">
                      {action.label}
                    </p>
                    <p className="mt-1 text-sm text-gray-600">{action.description}</p>
                  </div>
                </div>
              </Link>
            )
          })}
        </div>
      </section>

      {/* Core Workflows */}
      <section>
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Core workflows</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {featureWorkflows.map((feature) => {
            const Icon = feature.icon
            return (
              <Link
                key={feature.path}
                to={feature.path}
                className="card hover:shadow-md transition-shadow duration-200 group"
              >
                <div className="flex items-start space-x-4">
                  <div
                    className={`${feature.color} w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform duration-200`}
                  >
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                  <div className="flex-1">
                    <h3 className="font-semibold text-gray-900 mb-1 group-hover:text-primary-600 transition-colors">
                      {feature.title}
                    </h3>
                    <p className="text-sm text-gray-600">{feature.description}</p>
                  </div>
                </div>
              </Link>
            )
          })}
        </div>
      </section>

      {/* Recommendations & Insights */}
      <section className="grid grid-cols-1 gap-6 lg:grid-cols-[1.6fr_1fr]">
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Recommended for you</h2>
            <Link to="/dashboard/templates" className="text-sm font-semibold text-primary-600 hover:text-primary-500">
              Browse more
            </Link>
          </div>
          <div className="space-y-4">
            {recommendedTemplates.map((template) => {
              const Icon = template.icon
              return (
                <Link
                  key={template.title}
                  to={template.path}
                  className="flex items-start gap-4 rounded-lg border border-gray-100 px-4 py-3 transition hover:border-primary-200 hover:bg-primary-50/40"
                >
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-50 text-primary-600">
                    <Icon className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="font-medium text-gray-900">{template.title}</p>
                    <p className="text-sm text-gray-600">{template.description}</p>
                  </div>
                </Link>
              )
            })}
          </div>
        </div>

        <div className="card space-y-4">
          <h2 className="text-lg font-semibold text-gray-900">Insights & updates</h2>
          <div className="space-y-4">
            {insightHighlights.map((insight) => {
              const Icon = insight.icon
              return (
                <div key={insight.title} className="flex gap-3 rounded-lg bg-gray-50 px-4 py-3">
                  <div className="flex h-8 w-8 items-center justify-center rounded-md bg-white text-primary-600 shadow">
                    <Icon className="h-4 w-4" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-gray-900">{insight.title}</p>
                    <p className="text-sm text-gray-600">{insight.description}</p>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </section>
    </div>
  )
}

export default DashboardHome


